classDiagram
    class PayrollHub{
        + List employee_list
        + calculate_payroll(employee: Employee) -> Employee
        + add_employee_info_to_database()
        + add_employee_info_to_file()
    }